Api/Product.php
DataFixtures/ORM/DeliveryStatuses/LoadDeliveryStatuses.php
DataFixtures/delivery-statuses.xml
Entity/DeliveryStatus.php
Product/ProductManager.php

__Tasks:__
| Tests pass?   | none

[BUGFIX] fixed default delivery status and api entity

---

Admin/SuluProductAdmin.php
Api/Attribute.php
Api/AttributeValue.php
Api/Product.php
Controller/ProductMediaController.php
Entity/Attribute.php
Entity/BaseProduct.php
Entity/ProductInterface.php
Product/AttributeManager.php
Product/AttributeValueManager.php
Product/ProductManager.php
Resources/config/doctrine/Attribute.orm.xml
Resources/config/doctrine/BaseProduct.orm.xml

__Tasks:__
| Tests pass?   | yes

[BUGFIX] fixed bug when adding media to product

---

Product/ProductManager.php
Resources/translations/sulu/backend.de.xlf
Resources/translations/sulu/backend.en.xlf

__Tasks:__
| Tests pass?   | none
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/864

[BUGFIX] fixed table header, field descriptor

---

Api/Attribute.php

__Tasks:__
Informations: 
Attribute API returned wrong link.
API Link: http://pool-alpin.lo/admin/api/attributes/1

[BUGFIX] Attribute API fix

---

Api/Product.php

Update Product API

---

Api/Product.php

__Tasks:__
| Tests pass?   | yes

[FEATURE] removed unneeded parameter

---

Api/ProductAttribute.php
Controller/TemplateController.php
Product/ProductManager.php
Resources/public/js/components/products/components/attributes/main.js
Resources/translations/sulu/backend.de.xlf

__Tasks:__
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/800

Productattributes

---

Resources/public/js/components/products/components/attributes/main.js

__Tasks:__
__Informations: If you don't select an attribute in the add overlay, the first one is selected

Add check for not selected

---

Api/SpecialPrice.php
Entity/SpecialPrice.php
Product/ProductManager.php
Resources/config/doctrine/SpecialPrice.orm.xml
Resources/public/js/components/bulk-price/bulk-price.html
Resources/public/js/components/bulk-price/main.js

__Tasks:__
__Informations: changes the names to startDate and endDate to avoid confusion in backend
and frontend

name changes backend & fronted

---

Entity/SpecialPriceRepository.php

__Tasks:__
__Informations: a leftover from the name change of special price dates

query change

---

Api/Product.php
Product/ProductPriceManager.php

__Tasks:__
__Informations: special price get
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1149

Special price

---

Resources/public/js/components/bulk-price/main.js
Resources/public/js/components/price-list/main.js
Resources/public/js/components/products/components/attributes/main.js
Resources/public/js/components/products/components/detail-form/main.js
Resources/public/js/components/products/components/media/main.js
Resources/public/js/components/products/components/pricing/main.js
Resources/public/js/components/products/main.js

__Tasks:__
__Informations_: Bug fix - when you switch tabs saved data is not shown 
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1218, https://github.com/sulu-io/SuluProductBundle/issues/157

[BUGFIX] tab switch bug

---

Resources/public/js/components/products/components/detail-form/main.js

__Tasks:__
__Informations: cannot add new product
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1281

[BUGFIX] repaired product add

---

Resources/public/js/components/products/components/detail-form/main.js
Resources/public/js/components/products/components/media/main.js
Resources/public/js/components/products/components/pricing/main.js

__Tasks:__
__Informations: product save bugfix
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1277

[BUGFIX] is numeric check of id at product save

---

Resources/public/js/components/products/components/detail-form/main.js
Resources/public/js/components/products/components/pricing/main.js

__Tasks:__
__Informations: remove isAlphaNumeric check

[BUGFIX] remove isAlphaNumeric

---

Resources/public/js/components/products/components/attributes/main.js

__Tasks:__
__Informations: cannot change status in product attributes tab to active/inactive
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1207

[BUGFIX] cannot change status of product in attributes tab to active/inactive

---

Controller/TemplateController.php

__Tasks:__
__Informations: tax rates in select box at product -> prices tab are not translated
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/571

[BUGFIX] translations for tax rate fix

---

Api/Product.php

__Tasks:__
__Informations: display special price on start site
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1351

[FEATURE] Display special price on start site

---

Controller/ProductMediaController.php

__Tasks:__
__Informations: cannot delete media when price is not set
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1344

[BUGFIX] cannot delete media when price is not set

---

.travis.yml
Entity/BaseProduct.php
Product/ProductManager.php

__Tasks:__
| Tests pass?   | none
| Fixed tickets | https://github.com/massiveart/POOL-ALPIN/issues/1607

[BUGFIX] removed default value for product cost

---

Entity/SpecialPriceRepository.php
Product/Exception/ProductNotActiveException.php
Product/ProductManager.php
composer.json

only return special prices of active products in ``findAllCurrent`` function

[FEATURE] Added exception when product not active; cleanups

---

Entity/Unit.php
Product/ProductPriceManagerInterface.php

Implemented fallback for unit translation

[BUGFIX] Removed default locale from function declaration

---

.gitignore
CHANGELOG.md
DependencyInjection/SuluProductExtension.php
README.md
Tests/Functional/Controller/ProductControllerTest.php
Tests/Functional/Controller/VariantControllerTest.php
Tests/app/AppKernel.php
UPGRADE.md
Validation/Products/getActionSchema.json
composer.json

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | yes
| Related issues/PRs | none
| License | MIT
This PR includes the SuluValidationBundle into the product bundle (https://github.com/sulu/SuluValidationBundle).
The `GET product by id` api is now checked for a locale.
`/admin/api/products/1` is not working anymore, you now need to specify a locale:
`/admin/api/products/1?locale=en`

[FEATURE] Added basic validation

---

CHANGELOG.md
Product/AttributeManager.php
Resources/config/doctrine/CountryTax.orm.xml
Resources/config/doctrine/ProductAttribute.orm.xml
Resources/config/doctrine/SpecialPrice.orm.xml
Tests/Functional/Controller/ProductAddonControllerTest.php
Tests/Functional/Controller/ProductControllerTest.php

| Q | A
| --- | ---
| Bug fix? | yes
| Fixed tickets | fixes -
| Related issues/PRs | -
| License | MIT
This fixes the doctrine schema validation errors in the product bundle.
Why not?
~~~php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)
$foo = new Foo();
// Now we can do
$foo->doSomething();
~~~
Describe BC breaks/deprecations here. (remove this section if not needed)

[HOTFIX] Fixed schema validation

---

CHANGELOG.md
Product/ProductLocaleManager.php

| Q | A
| --- | ---
| Bug fix? | yes
Improved ProductLocaleManager to check if requested locale is available.

[BUGFIX] Improved ProductLocaleManager to check if requested locale is available

---

CHANGELOG.md
Product/ProductLocaleManager.php

| Q | A
| --- | ---
| Bug fix? | yes
ProductLocaleManager: Made user nullable.

[BUGFIX] ProductLocaleManager: Made user nullable

---

CHANGELOG.md
Resources/public/js/components/products/components/edit/attributes/main.js

| Q | A
| --- | ---
| Bug fix? | yes
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
Fixes duplicated results on attributes field.
Attributes autocomplete field got duplicated results.

removed prefatch url from autocomplete options

---

CHANGELOG.md

| Q | A
| --- | ---
| Bug fix? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
Explain the contents of the PR.
Which problem does the PR fix? (remove this section if you linked an issue above)
~~~php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)
$foo = new Foo();
// Now we can do
$foo->doSomething();
~~~
Describe BC breaks/deprecations here. (remove this section if not needed)

Merge develop in master
